const levels = [
    { phrase: "DURIAN RAJA BUAH", clues: [{w:"DURIAN", t:"Buah berduri bau menyengat"}, {w:"RAJA", t:"Pemimpin laki-laki di kerajaan"}] },
    { phrase: "KOPLO ASLI INDONESIA", clues: [{w:"KOPLO", t:"Aliran musik kendang"}, {w:"ASLI", t:"Bukan barang KW atau palsu"}] },
    { phrase: "SMARTPHONE CANGGIH", clues: [{w:"CANGGIH", t:"Teknologi masa kini"}, {w:"SMART", t:"Bahasa Inggrisnya pintar"}] },
    { phrase: "FREE FIRE GAME BURIK", clues: [{w:"GAME", t:"Permainan digital"}, {w:"BURIK", t:"Ejekan buat grafik rendah"}] },
    { phrase: "JAKARTA IBUKOTA KITA", clues: [{w:"KITA", t:"Aku dan kamu"}, {w:"IBUKOTA", t:"Pusat pemerintahan negara"}] },
    { phrase: "MATEMATIKA SANGAT SULIT", clues: [{w:"SULIT", t:"Lawan kata mudah"}, {w:"SANGAT", t:"Kata penekanan (banget)"}] },
    { phrase: "BOROBUDUR CANDI MEGAH", clues: [{w:"MEGAH", t:"Besar dan mewah"}, {w:"CANDI", t:"Bangunan bersejarah Hindu-Budha"}] },
    { phrase: "NASI GORENG ENAK", clues: [{w:"ENAK", t:"Rasa makanan mantap"}, {w:"NASI", t:"Makanan pokok orang Indo"}] },
    { phrase: "VALORANT GAME FPS", clues: [{w:"GAME", t:"Hiburan di PC/HP"}, {w:"FPS", t:"Genre tembak-tembakan"}] },
    { phrase: "UPACARA HARI SENIN", clues: [{w:"HARI", t:"Senin sampai Minggu"}, {w:"UPACARA", t:"Kegiatan rutin Senin pagi di sekolah"}] },
    { phrase: "INDOMIE SELERA RAKYAT", clues: [{w:"SELERA", t:"Keinginan atau nafsu makan"}, {w:"RAKYAT", t:"Seluruh penduduk negara"}] },
    { phrase: "SOLDER PANAS SEKALI", clues: [{w:"PANAS", t:"Lawan kata dingin"}, {w:"SOLDER", t:"Alat buat nempel timah ke PCB"}] },
    { phrase: "MOBILE LEGENDS RAME", clues: [{w:"RAME", t:"Banyak orang atau padat"}, {w:"MOBILE", t:"clue MOBIL tambahin E"}] },
    { phrase: "ES KRIM RASA COKELAT", clues: [{w:"RASA", t:"Manis, asin, atau pahit"}, {w:"KRIM", t:"Tekstur lembut di atas cone"}] },
    { phrase: "TIKTOK VIRAL", clues: [{w:"VIRAL", t:"Terkenal banyak yang tau"}, {w:"TIKTOK", t:"sering di scroll icon hitam"}] },
    { phrase: "MATAHARI PUSAT SURYA", clues: [{w:"PUSAT", t:"Titik tengah"}, {w:"SURYA", t:"Nama lain sistem tata planet kita"}] },
    { phrase: "BELAJAR BIAR PINTAR", clues: [{w:"BIAR", t:"supaya dalam bahasa kampung bi.r"}, {w:"PINTAR", t:"Lawan kata bodoh"}] },
    { phrase: "INDONESIA TANAH AIR", clues: [{w:"TANAH", t:"Tempat berpijak atau bumi"}, {w:"AIR", t:"Benda cair yang diminum"}] },
    { phrase: "TERIMA KASIH", clues: [{w:"TERIMA", t:"Lawan kata kasih (memberi)"}, {w:"KASIH", t:"lawan kata terima"}] },
    { phrase: "GAK ADA LAWAN", clues: [{w:"GAK", t:"menolak"}, {w:"LAWAN", t:"Lawan kata kawan"}] },
    { phrase: "ANJING BEBAN", clues: [{w:"ANJING", t:"Nama hewan seribg disebut saat marah"}, {w:"BEBAN", t:"Teman yang gak berguna di tim game"}] },
    { phrase: "JANGAN SOMBONG", clues: [{w:"JANGAN", t:"Larangan"}, {w:"SOMBONG", t:"pamer"}] },
    { phrase: "PINJAM DULU SERATUS", clues: [{w:"SERATUS", t:"Nominal uang yang sering dipinjam tapi gak balik"}, {w:"PINJAM", t:"Minjem barang atau uang"}] },
    { phrase: "YGY JANGAN LUPA BAHAGIA", clues: [{w:"YGY", t:"Singkatan dari Ya Guys Ya"}, {w:"LUPA", t:"Lawan kata ingat"}] },
    { phrase: "SIPALING SKENA", clues: [{w:"SKENA", t:"Istilah buat orang yang gayanya nyentrik"}, {w:"SIPALING", t:"Julukan buat orang yang merasa paling hebat"}] },
    { phrase: "GHOSTING ITU SAKIT HATI", clues: [{w:"SAKIT", t:"Rasanya ditinggal pas lagi sayang"}, {w:"GHOSTING", t:"Ngilang kek hantu b inggris"}] },
    { phrase: "LU PUNYA DUIT LU PUNYA KUASA", clues: [{w:"DUIT", t:"Uang"}, {w:"KUASA", t:"Wewenang atau kekuatan"}] },
    { phrase: "STARBOY JANGAN SOMBONG", clues: [{w:"SOMBONG", t:"Angkuh"}, {w:"STARBOY", t:"Laki-laki yang merasa jadi pusat perhatian"}] },
    { phrase: "CUMA FRIENDS DENGAN BENEFIT", clues: [{w:"BENEFIT", t:"Keuntungan"}, {w:"FRIENDS", t:"Teman (Bahasa Inggris)"}] },
    { phrase: "VALID NO DEBAT", clues: [{w:"VALID", t:"Sah atau benar banget"}, {w:"NO", t:"b inggris tidak"}, {w:"DEBAT", t:"Adu argumen"}] }
];
